name: FurniFit Backend Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lpediabackend    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './backend/publish'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: |
          cd backend
          dotnet build FurniFit.csproj --configuration Release
          dotnet publish FurniFit.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISHING_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
